# Dependencies

# kramdown to support footnotes
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title

# Setup
title:            Dennis Tenen
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com

# Required if you want to move pages into a a separate directory
include: ['_pages']
relative_permalinks: false

author:
  name:           'Dennis Tenen'
  url:            https://twitter.com/dennistenen

# number of posts on each page
paginate:         3

# Custom vars

github:
  repo:           https://github.com/denten/denten.github.io
